export interface WordPack {
  id: string;
  name: string;
  section: string;
  icon: string;
  words: string[];
}

export const SECTIONS = [
  "ESSENTIALS",
  "TRICKY LETTERS",
  "BINGO STEMS",
  "HIGH PROBABILITY",
  "VOWEL MANAGEMENT",
] as const;

export const WORD_PACKS: WordPack[] = [
  {
    id: "2-letter",
    name: "2-Letter Words",
    section: "ESSENTIALS",
    icon: "Aa",
    words: [
      "AA", "AB", "AD", "AE", "AG", "AH", "AI", "AL", "AM", "AN",
      "AR", "AS", "AT", "AW", "AX", "AY", "BA", "BE", "BI", "BO",
      "BY", "DA", "DE", "DO", "ED", "EF", "EH", "EL", "EM", "EN",
      "ER", "ES", "ET", "EW", "EX", "FA", "FE", "GI", "GO", "HA",
      "HE", "HI", "HM", "HO", "ID", "IF", "IN", "IS", "IT", "JO",
      "KA", "KI", "LA", "LI", "LO", "MA", "ME", "MI", "MM", "MO",
      "MU", "MY", "NA", "NE", "NO", "NU", "OD", "OE", "OF", "OH",
      "OI", "OK", "OM", "ON", "OP", "OR", "OS", "OW", "OX", "OY",
      "PA", "PE", "PI", "PO", "QI", "RE", "SH", "SI", "SO", "TA",
      "TE", "TI", "TO", "UH", "UM", "UN", "UP", "US", "UT", "WE",
      "WO", "XI", "XU", "YA", "YE", "YO", "ZA",
    ],
  },
  {
    id: "3-letter",
    name: "3-Letter Words",
    section: "ESSENTIALS",
    icon: "Abc",
    words: [
      "AAH", "AAL", "AAS", "ABA", "ABS", "ABY", "ACE", "ACK", "ACT", "ADD",
      "ADO", "ADS", "ADZ", "AFF", "AFT", "AGA", "AGE", "AGO", "AGS", "AHA",
      "AHI", "AHS", "AID", "AIL", "AIM", "AIN", "AIR", "AIS", "AIT", "AJI",
      "ALA", "ALB", "ALE", "ALL", "ALP", "ALS", "ALT", "AMA", "AMI", "AMP",
      "AMU", "ANA", "AND", "ANE", "ANI", "ANT", "ANY", "APE", "APO", "APP",
      "APT", "ARB", "ARC", "ARE", "ARF", "ARK", "ARM", "ARO", "ARS", "ART",
      "ASH", "ASK", "ASP", "ASS", "ATE", "ATS", "ATT", "AUK", "AVA", "AVE",
      "AVO", "AWA", "AWE", "AWL", "AWN", "AXE", "AYE", "AYS", "AZO",
      "BAA", "BAD", "BAE", "BAG", "BAH", "BAL", "BAM", "BAN", "BAP", "BAR",
      "BAS", "BAT", "BAY", "BED", "BEE", "BEG", "BEL", "BEN", "BES", "BET",
      "BEY", "BIB", "BID", "BIG", "BIN", "BIO", "BIS", "BIT", "BIZ", "BOA",
      "BOB", "BOD", "BOG", "BOO", "BOP", "BOS", "BOT", "BOW", "BOX", "BOY",
      "BRA", "BRO", "BRR", "BUB", "BUD", "BUG", "BUM", "BUN", "BUR", "BUS",
      "BUT", "BUY", "BYE", "BYS",
      "CAB", "CAD", "CAF", "CAL", "CAM", "CAN", "CAP", "CAR", "CAT", "CAW",
      "CAY", "CEE", "CEL", "CEP", "CHI", "CIG", "CIS", "COB", "COD", "COG",
      "COL", "CON", "COO", "COP", "COR", "COS", "COT", "COW", "COX", "COY",
      "COZ", "CRU", "CRY", "CUB", "CUD", "CUE", "CUM", "CUP", "CUR", "CUT",
      "CUZ", "CWM",
      "DAB", "DAD", "DAG", "DAH", "DAK", "DAL", "DAM", "DAN", "DAP", "DAS",
      "DAW", "DAY", "DEB", "DEE", "DEF", "DEL", "DEN", "DEP", "DEV", "DEW",
      "DEX", "DEY", "DIB", "DID", "DIE", "DIF", "DIG", "DIM", "DIN", "DIP",
      "DIS", "DIT", "DOC", "DOE", "DOG", "DOH", "DOL", "DOM", "DON", "DOR",
      "DOS", "DOT", "DOW", "DOX", "DRY", "DUB", "DUD", "DUE", "DUG", "DUH",
      "DUI", "DUM", "DUN", "DUO", "DUP", "DYE",
      "EAR", "EAT", "EAU", "EBB", "ECO", "ECU", "EDH", "EDS", "EEK", "EEL",
      "EEW", "EFF", "EFS", "EFT", "EGG", "EGO", "EKE", "ELD", "ELF", "ELK",
      "ELL", "ELM", "ELS", "EME", "EMO", "EMS", "EMU", "END", "ENG", "ENS",
      "EON", "ERA", "ERE", "ERG", "ERN", "ERR", "ERS", "ESS", "EST", "ETA",
      "ETH", "EVE", "EWE", "EYE",
      "FAB", "FAD", "FAG", "FAH", "FAM", "FAN", "FAR", "FAS", "FAT", "FAV",
      "FAX", "FAY", "FED", "FEE", "FEH", "FEM", "FEN", "FER", "FES", "FET",
      "FEU", "FEW", "FEY", "FEZ", "FIB", "FID", "FIE", "FIG", "FIL", "FIN",
      "FIR", "FIT", "FIX", "FIZ", "FLU", "FLY", "FOB", "FOE", "FOG", "FOH",
      "FON", "FOO", "FOP", "FOR", "FOU", "FOX", "FOY", "FRO", "FRY", "FUB",
      "FUD", "FUG", "FUN", "FUR",
      "GAB", "GAD", "GAE", "GAG", "GAL", "GAM", "GAN", "GAP", "GAR", "GAS",
      "GAT", "GAY", "GED", "GEE", "GEL", "GEM", "GEN", "GET", "GEY", "GHI",
      "GIB", "GID", "GIE", "GIF", "GIG", "GIN", "GIP", "GIS", "GIT", "GNU",
      "GOA", "GOB", "GOD", "GOO", "GOR", "GOS", "GOT", "GOX", "GOY", "GRR",
      "GUL", "GUM", "GUN", "GUT", "GUV", "GUY", "GYM", "GYP",
      "HAD", "HAE", "HAG", "HAH", "HAJ", "HAM", "HAO", "HAP", "HAS", "HAT",
      "HAW", "HAY", "HEH", "HEM", "HEN", "HEP", "HER", "HES", "HET", "HEW",
      "HEX", "HEY", "HIC", "HID", "HIE", "HIM", "HIN", "HIP", "HIS", "HIT",
      "HMM", "HOB", "HOD", "HOE", "HOG", "HOM", "HON", "HOO", "HOP", "HOS",
      "HOT", "HOW", "HOY", "HUB", "HUE", "HUG", "HUH", "HUM", "HUN", "HUP",
      "HUT", "HYP",
      "ICE", "ICH", "ICK", "ICY", "IDS", "IFF", "IFS", "IGG", "ILK", "ILL",
      "IMP", "INK", "INN", "INS", "ION", "IRE", "IRK", "ISM", "ITS", "IVY",
      "JAB", "JAG", "JAM", "JAR", "JAW", "JAY", "JEE", "JET", "JEU", "JIB",
      "JIG", "JIN", "JOB", "JOE", "JOG", "JOT", "JOW", "JOY", "JUG", "JUN",
      "JUS", "JUT",
      "KAB", "KAE", "KAF", "KAS", "KAT", "KAY", "KEA", "KEF", "KEG", "KEN",
      "KEP", "KEX", "KEY", "KHI", "KID", "KIF", "KIN", "KIP", "KIR", "KIS",
      "KIT", "KOA", "KOB", "KOI", "KOP", "KOR", "KOS", "KUE", "KYE",
      "LAB", "LAC", "LAD", "LAG", "LAH", "LAM", "LAP", "LAR", "LAS", "LAT",
      "LAV", "LAW", "LAX", "LAY", "LEA", "LED", "LEE", "LEG", "LEI", "LEK",
      "LET", "LEU", "LEV", "LEX", "LEY", "LIB", "LID", "LIE", "LIN", "LIP",
      "LIS", "LIT", "LOB", "LOC", "LOG", "LOO", "LOP", "LOR", "LOT", "LOW",
      "LOX", "LUD", "LUG", "LUM", "LUN", "LUV", "LUX", "LYE",
      "MAC", "MAD", "MAE", "MAG", "MAM", "MAN", "MAP", "MAR", "MAS", "MAT",
      "MAW", "MAX", "MAY", "MED", "MEG", "MEH", "MEL", "MEM", "MEN", "MES",
      "MET", "MEW", "MHO", "MIB", "MIC", "MID", "MIG", "MIL", "MIM", "MIR",
      "MIS", "MIX", "MMM", "MOA", "MOB", "MOC", "MOD", "MOG", "MOI", "MOL",
      "MOM", "MON", "MOO", "MOP", "MOR", "MOS", "MOT", "MOW", "MUD", "MUG",
      "MUM", "MUN", "MUS", "MUT", "MUX", "MYC",
      "NAB", "NAE", "NAG", "NAH", "NAM", "NAN", "NAP", "NAV", "NAW", "NAY",
      "NEB", "NEE", "NEG", "NET", "NEW", "NIB", "NIL", "NIM", "NIP", "NIT",
      "NIX", "NOB", "NOD", "NOG", "NOH", "NOM", "NOO", "NOR", "NOS", "NOT",
      "NOW", "NTH", "NUB", "NUG", "NUN", "NUS", "NUT",
      "OAF", "OAK", "OAR", "OAT", "OBA", "OBE", "OBI", "OCA", "OCH", "ODA",
      "ODD", "ODE", "ODS", "OES", "OFF", "OFT", "OHM", "OHO", "OHS", "OIK",
      "OIL", "OKA", "OKE", "OLD", "OLE", "OMA", "OMS", "ONE", "ONO", "ONS",
      "OOF", "OOH", "OOT", "OPA", "OPE", "OPS", "OPT", "ORA", "ORB", "ORC",
      "ORE", "ORG", "ORS", "ORT", "OSE", "OUD", "OUR", "OUT", "OVA", "OWE",
      "OWL", "OWN", "OWT", "OXO", "OXY",
      "PAC", "PAD", "PAH", "PAK", "PAL", "PAM", "PAN", "PAP", "PAR", "PAS",
      "PAT", "PAW", "PAX", "PAY", "PEA", "PEC", "PED", "PEE", "PEG", "PEH",
      "PEN", "PEP", "PER", "PES", "PET", "PEW", "PHI", "PHO", "PHT", "PIA",
      "PIC", "PIE", "PIG", "PIN", "PIP", "PIS", "PIT", "PIU", "PIX", "PLY",
      "POD", "POH", "POI", "POL", "POM", "POO", "POP", "POS", "POT", "POW",
      "POX", "PRO", "PRY", "PSI", "PST", "PUB", "PUD", "PUG", "PUL", "PUN",
      "PUP", "PUR", "PUS", "PUT", "PWN", "PYA", "PYE", "PYX",
      "QAT", "QIS", "QUA",
      "RAD", "RAG", "RAH", "RAI", "RAJ", "RAM", "RAN", "RAP", "RAS", "RAT",
      "RAW", "RAX", "RAY", "REB", "REC", "RED", "REE", "REF", "REG", "REI",
      "REM", "REP", "RES", "RET", "REV", "REX", "REZ", "RHO", "RIA", "RIB",
      "RID", "RIF", "RIG", "RIM", "RIN", "RIP", "ROB", "ROC", "ROD", "ROE",
      "ROM", "ROO", "ROT", "ROW", "RUB", "RUE", "RUG", "RUM", "RUN", "RUT",
      "RYA", "RYE", "RYU",
      "SAB", "SAC", "SAD", "SAE", "SAG", "SAL", "SAN", "SAP", "SAT", "SAU",
      "SAW", "SAX", "SAY", "SEA", "SEC", "SEE", "SEG", "SEI", "SEL", "SEN",
      "SER", "SET", "SEV", "SEW", "SEX", "SEZ", "SHA", "SHE", "SHH", "SHO",
      "SHY", "SIB", "SIC", "SIG", "SIM", "SIN", "SIP", "SIR", "SIS", "SIT",
      "SIX", "SKA", "SKI", "SKY", "SLY", "SOB", "SOC", "SOD", "SOH", "SOL",
      "SOM", "SON", "SOP", "SOS", "SOT", "SOU", "SOW", "SOX", "SOY", "SPA",
      "SPY", "SRI", "STY", "SUB", "SUE", "SUK", "SUM", "SUN", "SUP", "SUQ",
      "SUS", "SYN",
      "TAB", "TAD", "TAE", "TAG", "TAJ", "TAM", "TAN", "TAO", "TAP", "TAR",
      "TAS", "TAT", "TAU", "TAV", "TAW", "TAX", "TEA", "TEC", "TED", "TEE",
      "TEG", "TEL", "TEN", "TES", "TET", "TEW", "THE", "THO", "THY", "TIC",
      "TIE", "TIL", "TIN", "TIP", "TIS", "TIT", "TIX", "TIZ", "TOD", "TOE",
      "TOG", "TOM", "TON", "TOO", "TOP", "TOR", "TOT", "TOW", "TOY", "TRY",
      "TSK", "TUB", "TUG", "TUI", "TUM", "TUN", "TUP", "TUT", "TUX", "TWA",
      "TWO", "TYE",
      "UDO", "UGH", "UKE", "ULU", "UMM", "UMP", "UMS", "UNI", "UNS", "UPO",
      "UPS", "URB", "URD", "URN", "URP", "USE", "UTA", "UTE", "UTS",
      "VAC", "VAN", "VAR", "VAS", "VAT", "VAU", "VAV", "VAW", "VAX", "VEE",
      "VEG", "VET", "VEX", "VIA", "VID", "VIE", "VIG", "VIM", "VIN", "VIS",
      "VOE", "VOG", "VOW", "VOX", "VUG", "VUM",
      "WAB", "WAD", "WAE", "WAG", "WAN", "WAP", "WAR", "WAS", "WAT", "WAW",
      "WAX", "WAY", "WEB", "WED", "WEE", "WEN", "WET", "WHA", "WHO", "WHY",
      "WIG", "WIN", "WIS", "WIT", "WIZ", "WOE", "WOK", "WON", "WOO", "WOS",
      "WOT", "WOW", "WRY", "WUD", "WUZ", "WYE", "WYN",
      "XED", "XIS",
      "YAG", "YAH", "YAK", "YAM", "YAP", "YAR", "YAS", "YAW", "YAY", "YEA",
      "YEH", "YEN", "YEP", "YER", "YES", "YET", "YEW", "YEZ", "YIN", "YIP",
      "YOB", "YOD", "YOK", "YOM", "YON", "YOU", "YOW", "YUK", "YUM", "YUP",
      "ZAG", "ZAP", "ZAS", "ZAX", "ZED", "ZEE", "ZEK", "ZEN", "ZEP", "ZIG",
      "ZIN", "ZIP", "ZIT", "ZOA", "ZOO", "ZUZ", "ZZZ",
    ],
  },
  {
    id: "short-j",
    name: "Short J Words",
    section: "TRICKY LETTERS",
    icon: "J",
    words: [
      "JO",
      "AJI", "HAJ", "JAB", "JAG", "JAM", "JAR", "JAW", "JAY", "JEE",
      "JET", "JEU", "JIB", "JIG", "JIN", "JOB", "JOE", "JOG", "JOT",
      "JOW", "JOY", "JUG", "JUN", "JUS", "JUT", "RAJ", "TAJ",
      "AJAR", "AJEE", "AJIS", "DJIN", "DOJO", "FUJI", "GOJI", "HADJ",
      "HAJI", "HAJJ", "JABS", "JACK", "JADE", "JAGG", "JAGS", "JAIL",
      "JAKE", "JAMB", "JAMS", "JANE", "JAPE", "JARL", "JARS", "JATO",
      "JAUK", "JAUP", "JAVA", "JAWS", "JAYS", "JAZZ", "JEAN", "JEDI",
      "JEED", "JEEP", "JEER", "JEES", "JEEZ", "JEFE", "JEHU", "JELL",
      "JEON", "JERK", "JESS", "JEST", "JETE", "JETS", "JEUX", "JIAO",
      "JIBB", "JIBE", "JIBS", "JIFF", "JIGS", "JILL", "JILT", "JIMP",
      "JINK", "JINN", "JINS", "JINX", "JIRD", "JISM", "JIVE", "JIVY",
      "JIZZ", "JOBS", "JOCK", "JOES", "JOEY", "JOGS", "JOHN", "JOIN",
      "JOKE", "JOKY", "JOLE", "JOLT", "JOOK", "JOSH", "JOSS", "JOTA",
      "JOTS", "JOUK", "JOWL", "JOWS", "JOYS", "JUBA", "JUBE", "JUCO",
      "JUDO", "JUDY", "JUGA", "JUGS", "JUJU", "JUKE", "JUKU", "JUMP",
      "JUNK", "JUPE", "JURA", "JURY", "JUST", "JUTE", "JUTS", "KOJI",
      "MOJO", "PUJA", "RAJA", "SOJA", "SOJU", "YAJE",
    ],
  },
  {
    id: "short-q",
    name: "Short Q Words",
    section: "TRICKY LETTERS",
    icon: "Q",
    words: [
      "QI",
      "QAT", "QIS", "QUA", "SUQ",
      "AQUA", "CINQ", "QADI", "QAID", "QATS", "QOPH", "QUAD", "QUAG",
      "QUAI", "QUAY", "QUEY", "QUID", "QUIN", "QUIP", "QUIT", "QUIZ",
      "QUOD", "SUQS",
    ],
  },
  {
    id: "short-x",
    name: "Short X Words",
    section: "TRICKY LETTERS",
    icon: "X",
    words: [
      "AX", "EX", "OX", "XI", "XU",
      "AXE", "BOX", "COX", "DEX", "DOX", "FAX", "FIX", "FOX", "GOX",
      "HEX", "KEX", "LAX", "LEX", "LOX", "LUX", "MAX", "MIX", "MUX",
      "NIX", "OXO", "OXY", "PAX", "PIX", "POX", "PYX", "RAX", "REX",
      "SAX", "SEX", "SIX", "SOX", "TAX", "TIX", "TUX", "VAX", "VEX",
      "VOX", "WAX", "XED", "XIS", "ZAX",
      "APEX", "AXAL", "AXED", "AXEL", "AXES", "AXIL", "AXIS", "AXLE",
      "AXON", "BOXY", "BRUX", "CALX", "COAX", "COXA", "CRUX", "DEXY",
      "DOUX", "DOXX", "DOXY", "EAUX", "EXAM", "EXEC", "EXED", "EXES",
      "EXIT", "EXON", "EXPO", "FALX", "FAUX", "FIXT", "FLAX", "FLEX",
      "FLUX", "FOLX", "FOXY", "HOAX", "IBEX", "ILEX", "IXIA", "JEUX",
      "JINX", "LUXE", "LYNX", "MAXI", "MINX", "MIXT", "MOXA", "MPOX",
      "NEXT", "NIXE", "NIXY", "ONYX", "ORYX", "OXEN", "OXER", "OXES",
      "OXIC", "OXID", "OXIM", "PIXY", "PLEX", "POXY", "PREX", "ROUX",
      "SEXT", "SEXY", "TAXA", "TAXI", "TEXT", "VAXX", "VEXT", "WAXY",
      "XYST",
    ],
  },
  {
    id: "short-z",
    name: "Short Z Words",
    section: "TRICKY LETTERS",
    icon: "Z",
    words: [
      "ZA",
      "ADZ", "AZO", "BIZ", "COZ", "CUZ", "FEZ", "FIZ", "REZ", "SEZ",
      "TIZ", "WIZ", "WUZ", "YEZ", "ZAG", "ZAP", "ZAS", "ZAX", "ZED",
      "ZEE", "ZEK", "ZEN", "ZEP", "ZIG", "ZIN", "ZIP", "ZIT", "ZOA",
      "ZOO", "ZUZ", "ZZZ",
      "ADZE", "AZAN", "AZON", "BAZZ", "BIZE", "BOZO", "BUZZ", "CAZH",
      "CHEZ", "COZY", "CZAR", "DAZE", "DITZ", "DOZE", "DOZY", "FAZE",
      "FIZZ", "FOZY", "FRIZ", "FUTZ", "FUZE", "FUZZ", "GAZE", "GEEZ",
      "GRIZ", "HAZE", "HAZY", "IZAR", "JAZZ", "JEEZ", "JIZZ", "LAZE",
      "LAZY", "LUTZ", "MAZE", "MAZY", "MEZE", "MOZO", "NAZI", "OOZE",
      "OOZY", "ORZO", "OUZO", "OYEZ", "PHIZ", "PREZ", "PUTZ", "QUIZ",
      "RAZE", "RAZZ", "RITZ", "SIZE", "SIZY", "SPAZ", "TIZZ", "TZAR",
      "WHIZ", "YUTZ", "YUZU", "ZAGS", "ZANY", "ZAPS", "ZARF", "ZEAL",
      "ZEBU", "ZEDA", "ZEDS", "ZEES", "ZEIN", "ZEKS", "ZENS", "ZEPS",
      "ZERK", "ZERO", "ZEST", "ZETA", "ZIGS", "ZILL", "ZINC", "ZINE",
      "ZING", "ZINS", "ZIPS", "ZITI", "ZITS", "ZIZZ", "ZOEA", "ZOIC",
      "ZONA", "ZONE", "ZONK", "ZOOM", "ZOON", "ZOOS", "ZORI", "ZOUK",
      "ZUKE", "ZYME",
    ],
  },
  {
    id: "tisane",
    name: "TISANE + ?",
    section: "BINGO STEMS",
    icon: "TI",
    words: [
      "ENTASIA", "TAENIAS",
      "BANTIES", "BASINET",
      "ACETINS", "CINEAST",
      "DESTAIN", "DETAINS", "INSTEAD", "NIDATES", "SAINTED", "SATINED", "STAINED",
      "ETESIAN",
      "FAINEST",
      "EASTING", "EATINGS", "GENISTA", "INGATES", "INGESTA", "SEATING", "TAGINES", "TEASING",
      "SHEITAN", "STHENIA",
      "ISATINE",
      "TAJINES",
      "INTAKES",
      "ELASTIN", "ENTAILS", "NAILSET", "SALIENT", "SALTINE", "SLAINTE", "TENAILS",
      "ETAMINS", "INMATES", "TAMEINS",
      "INANEST", "STANINE",
      "ATONIES",
      "PANTIES", "PATINES", "SAPIENT", "SPINATE",
      "ANESTRI", "ANTSIER", "NASTIER", "RATINES", "RETAINS", "RETINAS", "RETSINA", "STAINER", "STEARIN",
      "ENTASIS", "NASTIES", "SEITANS", "SESTINA", "TANSIES", "TISANES",
      "INSTATE", "SATINET",
      "AUNTIES", "SINUATE",
      "NAIVEST", "NATIVES", "VAINEST",
      "TAWNIES", "WANIEST",
      "ANTISEX", "SEXTAIN",
      "ZANIEST", "ZEATINS",
    ],
  },
  {
    id: "satire",
    name: "SATIRE + ?",
    section: "BINGO STEMS",
    icon: "SA",
    words: [
      "ARISTAE", "ASTERIA", "ATRESIA",
      "BAITERS", "BARITES", "REBAITS", "TERBIAS",
      "ATRESIC", "CRISTAE", "RACIEST", "STEARIC",
      "ARIDEST", "ASTRIDE", "DIASTER", "DISRATE", "STAIDER", "TARDIES", "TIRADES",
      "AERIEST", "SERIATE",
      "FAIREST",
      "AIGRETS", "GAITERS", "SEAGIRT", "STAGIER", "TRIAGES",
      "HASTIER",
      "AIRIEST",
      "REALIST", "RETAILS", "SALTIER", "SALTIRE", "SLATIER", "TAILERS",
      "IMARETS", "MAESTRI", "MISRATE", "SMARTIE",
      "ANESTRI", "ANTSIER", "NASTIER", "RATINES", "RETAINS", "RETINAS", "RETSINA", "STAINER", "STEARIN",
      "PARTIES", "PASTIER", "PIASTER", "PIASTRE", "PIRATES", "PRATIES", "TRAIPSE",
      "ARTSIER", "TARRIES", "TARSIER",
      "ARTSIES", "SATIRES",
      "ARTIEST", "ARTISTE", "ATTIRES", "IRATEST", "RATITES", "STRIATE", "TASTIER",
      "RAVIEST", "VASTIER", "VERITAS",
      "WAISTER", "WAITERS", "WARIEST", "WASTRIE",
    ],
  },
  {
    id: "retina",
    name: "RETINA + ?",
    section: "BINGO STEMS",
    icon: "RE",
    words: [
      "CERATIN", "CERTAIN", "CREATIN", "TACRINE",
      "ANTIRED", "DETRAIN", "TRAINED",
      "ARENITE", "RETINAE", "TRAINEE",
      "FAINTER",
      "GRANITE", "GRATINE", "INGRATE", "TANGIER", "TEARING",
      "HAIRNET", "INEARTH", "THERIAN",
      "INERTIA",
      "KERATIN",
      "LATRINE", "RATLINE", "RELIANT", "RETINAL", "TRENAIL",
      "MINARET", "RAIMENT",
      "ENTRAIN", "TRANNIE",
      "PAINTER", "PERTAIN", "REPAINT",
      "RETRAIN", "TERRAIN", "TRAINER",
      "ANESTRI", "ANTSIER", "NASTIER", "RATINES", "RETAINS", "RETINAS", "RETSINA", "STAINER", "STEARIN",
      "INTREAT", "ITERANT", "NATTIER", "NITRATE", "TERTIAN",
      "RUINATE", "TAURINE", "URANITE", "URINATE",
      "TAWNIER", "TINWARE",
    ],
  },
  {
    id: "hi-prob-7",
    name: "Hi Prob 7s",
    section: "HIGH PROBABILITY",
    icon: "7",
    words: [
      "ACONITE", "AEOLIAN", "AERADIO", "AEROSAT", "AGONIES", "AGONISE", "AILERON",
      "AIRDATE", "AIRLINE", "ALEURON", "ALIENED", "ALIENER", "ALIENOR", "ALINERS",
      "ALUNITE", "AMNIOTE", "ANEROID", "ANISEED", "ANISOLE", "ANODISE", "ARANEID",
      "ARENOSE", "ARENOUS", "ARIETTE", "AROINTS", "ATELIER", "ATONERS", "AUDIENT",
      "AUDITEE", "DARIOLE", "DEARIES", "DELAINE", "DELATOR", "DENARII", "DIATRON",
      "DILATER", "DINEROS", "DIORITE", "DONATES", "DOURINE", "EARNEST", "EASTERN",
      "EDITION", "EDITORS", "ELATION", "ELOINER", "ELUTION", "ENATION", "ENTERAL",
      "ENTIRES", "ENTOILS", "ENTRIES", "ERASION", "EROTICA", "ESTRIOL", "ETALONS",
      "ETERNAL", "GENITOR", "GOATIER", "GODETIA", "IDEATES", "INDORSE", "INEDITA",
      "INOSITE", "IODATES", "IONISER", "IRONIES", "IRONISE", "ISOLATE", "ISOLEAD",
      "LADRONE", "LEADIER", "LENTOID", "LEOTARD", "LINEATE", "LOANERS", "LOITERS",
      "MORAINE", "NAILERS", "NEAREST", "NEGATOR", "NEROLIS", "NEUROID", "NIOBATE",
      "NITERIE", "NOISIER", "NORITES", "OESTRIN", "OLESTRA", "ONLIEST", "ORATION",
      "ORDINES", "ORIENTS", "OUTDARE", "OUTEARN", "OUTLIER", "OUTLINE", "OUTREAD",
      "OUTRIDE", "RADIATE", "RADIOES", "RAINOUT", "RANDIES", "RATIONS", "READIES",
      "READOUT", "REALISE", "REDTAIL", "REGINAE", "RELOANS", "RENAILS", "RETINES",
      "RETINOL", "RETINUE", "REUNITE", "ROADIES", "ROASTED", "ROMAINE", "RONDEAU",
      "ROSEATE", "ROSINED", "ROUTINE", "SANDIER", "SANTERO", "SARDINE", "SENARII",
      "SENATOR", "SORDINE", "SORTIED", "SOUTANE", "STERANE", "STEROID", "STONIER",
      "STORIED", "STOURIE", "TAENIAE", "TAENITE", "TALONED", "TELERAN", "TIARAED",
      "TOADIES", "TOENAIL", "TOILERS", "TOLANES", "TORSADE", "TORULAE", "TRAILED",
      "TREASON", "TRIALED", "TRIENES", "TRIODES", "UNAIRED", "URALITE", "URANIDE",
      "URINOSE", "UTERINE",
    ],
  },
  {
    id: "hi-prob-8",
    name: "Hi Prob 8s",
    section: "HIGH PROBABILITY",
    icon: "8",
    words: [
      "ACTIONER", "ADROITER", "AERATION", "AEROLITE", "AERONAUT", "ALIENATE",
      "ANDESITE", "ANODISER", "ANOINTED", "ANOINTER", "ANORETIC", "ANTERIOR",
      "ANTIDOTE", "ANTIHERO", "ANTINODE", "ANTISERA", "AREOLATE", "AROINTED",
      "ARSENIDE", "ARSENITE", "ARTESIAN", "ASTEROID", "ASTONIED", "ATROPINE",
      "AUNTLIER", "BARITONE", "CREATION", "DAINTIER", "DATELINE", "DELATION",
      "DELETION", "DERATION", "DETAILER", "DETAINER", "DIASTOLE", "DOLERITE",
      "EARLIEST", "EARSTONE", "ELATERID", "ELATERIN", "ENTAILED", "ENTAILER",
      "ENTOILED", "ENTRAILS", "ERADIATE", "GELATION", "GERANIOL", "GRATINEE",
      "IDEATION", "IDOLATER", "INDORSEE", "INDURATE", "INERTIAE", "INERTIAL",
      "INSOLATE", "INTERAGE", "IODINATE", "IRONIEST", "ISOLATED", "LEARIEST",
      "LEGATION", "LINEATED", "NEARSIDE", "NONARIES", "NOTARIES", "NOTARISE",
      "OBTAINER", "OLEASTER", "ONERIEST", "ORDAINER", "ORDINATE", "ORGANDIE",
      "ORGANISE", "ORIENTAL", "ORIENTED", "OUTLEARN", "OUTLINER", "OUTRAISE",
      "RAINIEST", "RAISONNE", "RANDIEST", "RATANIES", "RATIONED", "REACTION",
      "READIEST", "REALTIES", "REANOINT", "REASONED", "REGIONAL", "RELATION",
      "RELOANED", "RENAILED", "REOBTAIN", "REORDAIN", "RESINATE", "RESONATE",
      "RETAILED", "RETAILOR", "RETAINED", "RETAINER", "RETINOID", "RETINULA",
      "ROTARIES", "RUINATED", "SANTERIA", "SATINIER", "SAUTOIRE", "SEATRAIN",
      "SEDATION", "SENORITA", "SERIATED", "SEROTINE", "SLANTIER", "SNOUTIER",
      "SODALITE", "SONATINE", "STEADIER", "STEARINE", "STRAINED", "TABORINE",
      "TAENIOID", "TAILORED", "TENTORIA", "TENURIAL", "TERATOID", "TETANOID",
      "TOASTIER", "TREENAIL", "UNEASIER", "URINATED",
    ],
  },
  {
    id: "i-dumps",
    name: "I Dumps",
    section: "VOWEL MANAGEMENT",
    icon: "II",
    words: [
      "BIDI", "HILI", "IBIS", "ILIA", "IMID", "IMPI", "INIA", "INTI",
      "IRID", "IRIS", "IWIS", "IXIA", "KIWI", "LIRI", "MIDI", "MINI",
      "MIRI", "NIDI", "NISI", "PIKI", "PILI", "TIKI", "TIPI", "TITI",
      "WIKI", "ZITI",
      "BIKINI", "BIMINI", "IMIDIC", "IRIDIC", "IRITIC", "IRITIS",
    ],
  },
  {
    id: "u-dumps",
    name: "U Dumps",
    section: "VOWEL MANAGEMENT",
    icon: "UU",
    words: [
      "ULU",
      "BUBU", "FUGU", "GURU", "JUJU", "JUKU", "KUDU", "KURU", "LUAU",
      "LULU", "MUMU", "PUDU", "PUPU", "SULU", "TUTU", "UNAU", "URUS",
      "YUZU",
      "MUUMUU",
    ],
  },
  {
    id: "vowel-dumps",
    name: "Vowel Dumps",
    section: "VOWEL MANAGEMENT",
    icon: "AE",
    words: [
      "AA", "AE", "AI", "OE", "OI",
      "EAU",
      "ACAI", "AEON", "AERO", "AGEE", "AGIO", "AGUE", "AIDE", "AJEE",
      "AKEE", "ALAE", "ALEE", "ALOE", "AMIA", "AMIE", "ANOA", "AQUA",
      "AREA", "ARIA", "ARIE", "ASEA", "AURA", "AUTO", "AWEE",
      "BEAU", "CIAO",
      "EASE", "EAUX", "EAVE", "EEEW", "EIDE", "EMEU", "EPEE", "ETUI", "EURO",
      "IDEA", "ILEA", "ILIA", "INIA", "IOTA", "IXIA",
      "JIAO", "LIEU", "LUAU",
      "MEOU", "MOUE",
      "NAOI",
      "OBIA", "OBOE", "ODEA", "OGEE", "OHIA", "OLEA", "OLEO", "OLIO",
      "OOZE", "OUTA", "OUZO", "OWIE",
      "PAUA", "QUAI", "RAIA", "ROUE",
      "TOEA", "UNAI", "UNAU", "UREA", "UVEA", "ZOEA",
      "AALII", "ADIEU", "AECIA", "AERIE", "AIOLI", "AIYEE", "AQUAE",
      "AREAE", "AUDIO", "AURAE", "AUREI",
      "COOEE", "EERIE",
      "LOOIE", "LOUIE",
      "MIAOU", "OIDIA", "OORIE", "OURIE", "OUTIE",
      "QUEUE",
      "URAEI", "ZOEAE",
    ],
  },
];

export function getPackById(id: string): WordPack | undefined {
  return WORD_PACKS.find((pack) => pack.id === id);
}

export function getMinWordLength(pack: WordPack): number {
  if (pack.words.length === 0) return 1;
  return Math.min(...pack.words.map((w) => w.length));
}

export function getMaxBlanks(pack: WordPack): number {
  return getMinWordLength(pack);
}
