export type PracticeWord = {
  word: string;
  definition: string;
};

export type PracticeList = {
  id: string;
  title: string;
  words: PracticeWord[];
  requiredLetters?: string[];
  quizSize?: number;
};

export const PRACTICE_LISTS: Record<string, PracticeList> = {
  debug: {
    id: "debug",
    title: "Debug (1 word)",
    words: [{ word: "CAT", definition: "A small domesticated feline" }],
  },
  "q-words": {
    id: "q-words",
    title: "Short Q Words",
    requiredLetters: ["Q"],
    words: [
      { word: "AQUA", definition: "Water or a light greenish-blue color" },
      { word: "CINQ", definition: "The number five" },
      { word: "QADI", definition: "An Islamic judge" },
      { word: "QAID", definition: "A Muslim judge" },
      { word: "QAT", definition: "A plant whose leaves are chewed as a stimulant" },
      { word: "QATS", definition: "Plural of QAT" },
      { word: "QI", definition: "The vital force in Chinese philosophy" },
      { word: "QIS", definition: "Plural of QI" },
      { word: "QOPH", definition: "A Hebrew letter" },
      { word: "QUA", definition: "In the capacity of" },
      { word: "QUAD", definition: "A quadrangle" },
      { word: "QUAG", definition: "A marshy area" },
      { word: "QUAI", definition: "A wharf" },
      { word: "QUAY", definition: "A landing place for ships" },
      { word: "QUEY", definition: "A young cow" },
      { word: "QUID", definition: "A British pound sterling" },
      { word: "QUIN", definition: "A quintuplet" },
      { word: "QUIP", definition: "A witty remark" },
      { word: "QUIT", definition: "To stop or give up" },
      { word: "QUIZ", definition: "A short test" },
      { word: "QUOD", definition: "A prison (slang)" },
      { word: "SUQ", definition: "An open-air marketplace" },
      { word: "SUQS", definition: "Plural of SUQ" },
    ],
  },
  "2-letter": {
    id: "2-letter",
    title: "2-Letter Words",
    quizSize: 15,
    words: [
      { word: "AA", definition: "A type of rough lava" },
      { word: "AB", definition: "An abdominal muscle" },
      { word: "AD", definition: "An advertisement" },
      { word: "AE", definition: "One (Scottish)" },
      { word: "AG", definition: "Relating to agriculture" },
      { word: "AH", definition: "An exclamation" },
      { word: "AI", definition: "A three-toed sloth" },
      { word: "AL", definition: "An East Indian tree" },
      { word: "AM", definition: "First person singular of BE" },
      { word: "AN", definition: "Used before words beginning with a vowel sound" },
      { word: "AR", definition: "The letter R" },
      { word: "AS", definition: "To the same degree" },
      { word: "AT", definition: "In the position of" },
      { word: "AW", definition: "An exclamation of protest" },
      { word: "AX", definition: "A chopping tool" },
      { word: "AY", definition: "An affirmative vote" },
      { word: "BA", definition: "The soul in Egyptian mythology" },
      { word: "BE", definition: "To exist" },
      { word: "BI", definition: "A bisexual person" },
      { word: "BO", definition: "A fellow" },
      { word: "BY", definition: "Near or beside" },
      { word: "DA", definition: "A Burmese knife" },
      { word: "DE", definition: "Of or from (used in names)" },
      { word: "DO", definition: "To perform" },
      { word: "ED", definition: "Education" },
      { word: "EF", definition: "The letter F" },
      { word: "EH", definition: "An exclamation of surprise" },
      { word: "EL", definition: "An elevated railway" },
      { word: "EM", definition: "A typographic unit of measurement" },
      { word: "EN", definition: "A typographic unit half the width of an em" },
      { word: "ER", definition: "An expression of hesitation" },
      { word: "ES", definition: "The letter S" },
      { word: "ET", definition: "Past tense of eat (dialectal)" },
      { word: "EW", definition: "An exclamation of disgust" },
      { word: "EX", definition: "A former partner" },
      { word: "FA", definition: "The fourth tone of a musical scale" },
      { word: "FE", definition: "A Hebrew letter" },
      { word: "GI", definition: "A martial arts uniform" },
      { word: "GO", definition: "To move or proceed" },
      { word: "HA", definition: "An exclamation of surprise" },
      { word: "HE", definition: "A male person" },
      { word: "HI", definition: "A greeting" },
      { word: "HM", definition: "An expression of thought" },
      { word: "HO", definition: "An exclamation to attract attention" },
      { word: "ID", definition: "A part of the psyche" },
      { word: "IF", definition: "A condition or supposition" },
      { word: "IN", definition: "Contained by" },
      { word: "IS", definition: "Third person singular of BE" },
      { word: "IT", definition: "A pronoun for a thing" },
      { word: "JO", definition: "A Scottish term of endearment" },
      { word: "KA", definition: "The spirit in Egyptian mythology" },
      { word: "KI", definition: "The vital force in Japanese philosophy" },
      { word: "LA", definition: "The sixth tone of a musical scale" },
      { word: "LI", definition: "A Chinese unit of distance" },
      { word: "LO", definition: "An exclamation used to attract attention" },
      { word: "MA", definition: "Mother" },
      { word: "ME", definition: "The objective case of I" },
      { word: "MI", definition: "The third tone of a musical scale" },
      { word: "MM", definition: "An expression of assent" },
      { word: "MO", definition: "A moment" },
      { word: "MU", definition: "A Greek letter" },
      { word: "MY", definition: "Belonging to me" },
      { word: "NA", definition: "No (Scottish)" },
      { word: "NE", definition: "Born as (used in names)" },
      { word: "NO", definition: "A negative response" },
      { word: "NU", definition: "A Greek letter" },
      { word: "OD", definition: "A hypothetical force" },
      { word: "OE", definition: "A whirlwind off the Faeroe Islands" },
      { word: "OF", definition: "Belonging to" },
      { word: "OH", definition: "An exclamation of surprise" },
      { word: "OI", definition: "An interjection to get attention" },
      { word: "OK", definition: "All right" },
      { word: "OM", definition: "A sacred syllable in Hinduism" },
      { word: "ON", definition: "In contact with a surface" },
      { word: "OP", definition: "A style of abstract art" },
      { word: "OR", definition: "A conjunction presenting alternatives" },
      { word: "OS", definition: "A bone" },
      { word: "OW", definition: "An exclamation of pain" },
      { word: "OX", definition: "A domesticated bovine" },
      { word: "OY", definition: "An exclamation of dismay" },
      { word: "PA", definition: "Father" },
      { word: "PE", definition: "A Hebrew letter" },
      { word: "PI", definition: "A Greek letter" },
      { word: "PO", definition: "A chamber pot" },
      { word: "QI", definition: "The vital force in Chinese philosophy" },
      { word: "RE", definition: "The second tone of a musical scale" },
      { word: "SH", definition: "Used to urge silence" },
      { word: "SI", definition: "The seventh tone of a musical scale" },
      { word: "SO", definition: "To such a degree" },
      { word: "TA", definition: "Thank you (British)" },
      { word: "TE", definition: "The seventh tone of a musical scale" },
      { word: "TI", definition: "A plant" },
      { word: "TO", definition: "In the direction of" },
      { word: "UH", definition: "An expression of hesitation" },
      { word: "UM", definition: "An expression of hesitation" },
      { word: "UN", definition: "One" },
      { word: "UP", definition: "Toward a higher position" },
      { word: "US", definition: "The objective case of we" },
      { word: "UT", definition: "The first tone of a musical scale" },
      { word: "WE", definition: "First person plural pronoun" },
      { word: "WO", definition: "An exclamation to stop a horse" },
      { word: "XI", definition: "A Greek letter" },
      { word: "XU", definition: "A Vietnamese monetary unit" },
      { word: "YA", definition: "You (informal)" },
      { word: "YE", definition: "You (archaic)" },
      { word: "YO", definition: "An exclamation to get attention" },
      { word: "ZA", definition: "Pizza (slang)" },
    ],
  },
};
