name: App Store

jobs:
  build_ios:
    name: Build iOS
    type: build
    params:
      platform: ios
  send_to_testflight:
    name: Send to App Store
    needs: [build_ios]
    type: testflight
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
