name: Development Build

jobs:
  android_development_build:
    type: build
    params:
      platform: android
      profile: development
  ios_device_development_build:
    type: build
    params:
      platform: ios
      profile: development
  ios_simulator_development_build:
    type: build
    params:
      platform: ios
      profile: development-simulator
