name: Create development builds

jobs:
  android_development_build:
    name: Build Android
    type: build
    params:
      platform: android
      profile: development
  ios_device_development_build:
    name: Build iOS device
    type: build
    image: macos-sequoia-15.5-xcode-26.0
    params:
      platform: ios
      profile: development
  ios_simulator_development_build:
    name: Build iOS simulator
    type: build
    image: macos-sequoia-15.5-xcode-26.0
    params:
      platform: ios
      profile: development-simulator
