name: Development Build

jobs:
  development-build:
    type: build
    params:
      platform: ios
      profile: development
  development-build-simulator:
    type: build
    params:
      platform: ios
      profile: development-simulator
  publish-update:
    type: update
    needs: [development-build, development-build-simulator]
    params:
      channel: development
