name: Production build and submit

jobs:
  production-build:
    type: build
    params:
      platform: ios
      profile: production
  submit:
    needs: [production-build]
    type: submit
    params:
      platform: ios
      build_id: ${{ jobs.production-build.outputs.build_id }}
