name: Upload to app stores

jobs:
  resolve_version:
    name: Resolve app version
    environment: production
    outputs:
      version: ${{ steps.resolve.outputs.version }}
    steps:
      - uses: eas/checkout
      - name: Resolve next available version
        id: resolve
        run: |
          VERSION=$(node .eas/scripts/resolve-version.mjs --mode next)
          echo "Resolved version: $VERSION"
          set-output version "$VERSION"

  deploy_web:
    name: Deploy web
    type: deploy
    params:
      prod: false

  build_ios:
    name: Build iOS
    needs: [resolve_version]
    type: build
    env:
      APP_VERSION: ${{ needs.resolve_version.outputs.version }}
    params:
      platform: ios
      profile: production

  app_store:
    name: Send to App Store
    needs: [build_ios]
    type: testflight
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}

  build_android:
    name: Build Android
    needs: [resolve_version]
    type: build
    env:
      APP_VERSION: ${{ needs.resolve_version.outputs.version }}
    params:
      platform: android
      profile: production

  play_store:
    name: Send to Play Store
    needs: [build_android]
    type: submit
    params:
      build_id: ${{ needs.build_android.outputs.build_id }}
